name: "ItemEditor"
main: "com.github.wyrdix.ItemEditorPlugin"
version: "0.0.3"
author: "Wyrdix"
default-permission: op
commands:
  edit_item:
    description: "Edit current held item"
    usage: "/edit_item"